name: CI with Ekstazi RTS

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  full-regression:
    name: Full Regression Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Full Regression Tests
        run: mvn ekstazi:clean test

      - name: Cache Ekstazi
        uses: actions/cache@v3
        with:
          path: .ekstazi
          key: ekstazi-cache-${{ github.ref }}-latest
          restore-keys: |
            ekstazi-cache-

  selective-regression:
    name: Selective Regression Test
    runs-on: ubuntu-latest
    needs: full-regression
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore Ekstazi Cache
        uses: actions/cache@v3
        with:
          path: .ekstazi
          key: ekstazi-cache-${{ github.ref }}-latest
          restore-keys: |
            ekstazi-cache-

      - name: Run Selective Regression Tests
        run: |
          mvn ekstazi:restore
          mvn ekstazi:select test
