name: CI with Regression Testing

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore Ekstazi Cache
        uses: actions/cache@v3
        with:
          path: .ekstazi 
          key: ${{ runner.os }}-maven-ekstazi-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-ekstazi-

      - name: Run Regression Testing
        run: mvn clean test
        
      - name: Save Ekstazi Cache
        uses: actions/cache/save@v3
        with:
          path: .ekstazi
          key: ${{ runner.os }}-maven-ekstazi-${{ hashFiles('**/pom.xml') }}
